**CONTENT**

.**1. Initial Setup**

.**2. Regarding the features slot (comprising 2 weeks), add 3 columns: a) same cluster next week? & b) inter-weeks distance to centroids difference**

.2.1. a) same cluster next week? - week 1 & week 2

.2.2. b) inter-weeks distance to centroids difference - week 1 & week 2

.2.3. features slot

.**3. Labels slot**

.**4. Generating the slots (features & labels) for the predictive models**

.4.1. fold 1

.4.2. fold 2

.4.3. fold 3

.4.4. fold 4

.4.5. fold 5

.4.6. fold 6

# Initial Setup

In [1]:
# libraries
import numpy as np
import pandas as pd

In [2]:
# weeks
df_w1 = pd.read_csv('features/features_p1.csv')
df_w2 = pd.read_csv('features/features_p2.csv')
df_w3 = pd.read_csv('features/features_p3.csv')
df_w4 = pd.read_csv('features/features_p4.csv')
df_w5 = pd.read_csv('features/features_p5.csv')
df_w6 = pd.read_csv('features/features_p6.csv')
df_w7 = pd.read_csv('features/features_p7.csv')
df_w8 = pd.read_csv('features/features_p8.csv')
df_w9 = pd.read_csv('features/features_p9.csv')
df_w10 = pd.read_csv('features/features_p10.csv')

In [3]:
# example - features week 1
df_w1

,device,00:00:00_06:45:00,06:45:00_11:45:00,11:45:00_19:15:00,19:15:00_23:59:59,Weekend/Holidays,d1,d2,d3,d4,...,m_cat2,b_cat2,m_cat3,b_cat3,m_cat4,b_cat4,m_cat5,b_cat5,m_cat6,b_cat6
0,0x4272D6BB7365FDB6394FC42F703839DB,0.050461,0.000000,0.000000,0.481321,0.468218,0.375394,0.379011,0.490525,0.122169,...,0.000221,0.732878,0.000846,0.762924,-0.007720,0.633758,0.000781,0.666360,0.000531,0.804662
1,0xCA6837254FF118AC46CDE43F1A1318CE,0.000000,0.325780,0.143208,0.531013,0.000000,0.599785,0.839675,0.715683,0.492269,...,0.069113,0.671561,-0.000139,0.779451,-0.022750,0.539172,0.008339,0.674011,-0.003609,0.819681
2,0x881C2A8AF6431AE8368AB0697A2D78EF,0.255797,0.486726,0.000000,0.000000,0.257477,0.596948,0.702344,0.473079,0.732784,...,-0.007065,0.684648,0.001659,0.759000,-0.009707,0.658167,0.001058,0.652899,0.001426,0.804055
3,0xDC7738C974D7FDF167D2246CE1397ED2,0.000000,0.143460,0.141106,0.252828,0.462605,0.154142,0.286633,0.417192,0.305615,...,0.002290,0.716728,0.000706,0.760829,-0.007624,0.684044,0.005778,0.638049,0.000237,0.805849
4,0x82E30D17D0B940C0719D852F46289BCB,0.184451,0.000000,0.228702,0.517844,0.069003,0.489512,0.744924,0.558700,0.370820,...,0.009785,0.673999,0.000833,0.758498,0.000192,0.661690,0.002195,0.654163,0.000380,0.804055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10637,0x977F0791EDCCE997196CCD7609925FD8,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,0.300964,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879
10638,0x58D0114966B9944735A9AA18C1C06998,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,1.223428,0.000000,1.243754,0.000000,1.151011,0.000000,1.186579,0.000000,0.225048
10639,0x7C4632CABFE3DE66CDE8D960B194779A,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,0.300964,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879
10640,0xFE9CF99DC53E3F33683F1FE3DB24F6FA,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,1.146770,0.000000,1.228205,0.000000,0.403448,0.000000,1.156130,0.000000,1.234596
10641,0x80281F3DBB94FAE38A7DEC8919BDC8D9,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,0.300964,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879

In [4]:
df_w1.columns

Index(['device', '00:00:00_06:45:00', '06:45:00_11:45:00', '11:45:00_19:15:00',
       '19:15:00_23:59:59', 'Weekend/Holidays', 'd1', 'd2', 'd3', 'd4', 'd5',
       'd6', 'TimeCluster', 'm1', 'b1', 'm2', 'b2', 'm3', 'b3', 'm4', 'b4',
       'm5', 'b5', 'm6', 'b6', 'Séries', 'Filmes', 'Documentários',
       'Informaçăo', 'Entretenimento', 'Generalistas', 'Desporto', 'Infantil',
       'Outros', 'Lifestyle', 'Internacionais', 'Música', 'd_cat1', 'd_cat2',
       'd_cat3', 'd_cat4', 'd_cat5', 'd_cat6', 'CatCluster', 'm_cat1',
       'b_cat1', 'm_cat2', 'b_cat2', 'm_cat3', 'b_cat3', 'm_cat4', 'b_cat4',
       'm_cat5', 'b_cat5', 'm_cat6', 'b_cat6'],
      dtype='object')

# Regarding the features slot (comprising 2 weeks), add 3 columns: a) same cluster next week? & **b)** inter-weeks distance to centroids difference

In the next sections (**2.1 & 2.2**), we will work only with **week 1** and **week 2**. 

Later on, in section **2.3**, we will implement a **custom function** able to perform the desired transforms for any features slot.

## a) same cluster next week? - week 1 & week 2

In [5]:
# check devices that appear in both weeks 
print("Checking devices that appear in both weeks: ")
print(df_w1['device'].isin(df_w2['device']).value_counts())

Checking devices that appear in both weeks:
True     7227
False    3415
Name: device, dtype: int64

In [6]:
# merge weeks based on devices that have activity on both periods (inner join)
df_merge = pd.merge(df_w1, df_w2, how='inner', left_on='device', right_on='device')

df_merge.columns

Index(['device', '00:00:00_06:45:00_x', '06:45:00_11:45:00_x',
       '11:45:00_19:15:00_x', '19:15:00_23:59:59_x', 'Weekend/Holidays_x',
       'd1_x', 'd2_x', 'd3_x', 'd4_x',
       ...
       'm_cat2_y', 'b_cat2_y', 'm_cat3_y', 'b_cat3_y', 'm_cat4_y', 'b_cat4_y',
       'm_cat5_y', 'b_cat5_y', 'm_cat6_y', 'b_cat6_y'],
      dtype='object', length=111)

In [7]:
# auxiliary function to add binary labels
def binary_label(x):
    if x == 0: 
        return 0 # device does not change cluster
    else:
        return 1 # device does change cluster

In [8]:
# add "change" columns to df_merge
df_merge['change_TimeCluster'] = df_merge['TimeCluster_x'] - df_merge['TimeCluster_y'] #**
df_merge['change_TimeCluster'] = df_merge['change_TimeCluster'].apply(binary_label) # add binary label
#** the device does not change cluster only if this difference is equal to 0

df_merge['change_CatCluster'] = df_merge['CatCluster_x'] - df_merge['CatCluster_x']
df_merge['change_CatCluster'].apply(binary_label)

# sanity check
print("# devices that change time cluster: ", (df_merge['change_TimeCluster'] != 0).sum())
print("# devices that don't change time cluster: ", (df_merge['change_TimeCluster'] == 0).sum())
print()
print("# devices that change categories cluster: ",(df_merge['change_CatCluster'] != 0).sum())
print("# devices that don't change categories cluster: ", (df_merge['change_CatCluster'] == 0).sum())

# devices that change time cluster:  4538
# devices that don't change time cluster:  2689

# devices that change categories cluster:  0
# devices that don't change categories cluster:  7227

In [9]:
# final features slot
df_merge

,device,00:00:00_06:45:00_x,06:45:00_11:45:00_x,11:45:00_19:15:00_x,19:15:00_23:59:59_x,Weekend/Holidays_x,d1_x,d2_x,d3_x,d4_x,...,m_cat3_y,b_cat3_y,m_cat4_y,b_cat4_y,m_cat5_y,b_cat5_y,m_cat6_y,b_cat6_y,change_TimeCluster,change_CatCluster
0,0x4272D6BB7365FDB6394FC42F703839DB,0.050461,0.000000,0.000000,0.481321,0.468218,0.375394,0.379011,0.490525,0.122169,...,0.000306,0.773360,0.000223,0.544427,0.000339,0.676097,0.000306,0.811440,0,0
1,0xCA6837254FF118AC46CDE43F1A1318CE,0.000000,0.325780,0.143208,0.531013,0.000000,0.599785,0.839675,0.715683,0.492269,...,0.000000,1.067325,0.000000,0.943002,0.000000,0.981589,0.000000,0.159367,0,0
2,0x881C2A8AF6431AE8368AB0697A2D78EF,0.255797,0.486726,0.000000,0.000000,0.257477,0.596948,0.702344,0.473079,0.732784,...,-0.000339,0.760919,-0.000495,0.657022,0.002090,0.648800,-0.001063,0.808443,1,0
3,0xDC7738C974D7FDF167D2246CE1397ED2,0.000000,0.143460,0.141106,0.252828,0.462605,0.154142,0.286633,0.417192,0.305615,...,0.000311,0.760789,0.000421,0.668139,-0.000974,0.655101,0.000222,0.805186,1,0
4,0x82E30D17D0B940C0719D852F46289BCB,0.184451,0.000000,0.228702,0.517844,0.069003,0.489512,0.744924,0.558700,0.370820,...,0.000351,0.759864,0.002433,0.657248,0.003036,0.649222,-0.000368,0.807025,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7222,0x458ACBCF1F2AEF82442226D7822B7922,0.000000,0.000000,1.000000,0.000000,0.000000,0.889257,1.186560,1.094750,1.121185,...,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879,1,0
7223,0x53025621D50B35AF1153585746252F52,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,0.273249,0.000000,1.197064,0.000000,1.191225,0.000000,1.280861,1,0
7224,0xD3E0AA1A149E2992158C78B1495D1B24,1.000000,0.000000,0.000000,0.000000,0.000000,1.093689,1.203285,0.748251,1.145344,...,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879,1,0
7225,0x8F2AFAD07C2F016220CF3FC9607C7BC2,0.000000,0.000000,0.000000,1.000000,0.000000,0.929919,1.074155,1.018596,0.627205,...,0.000000,0.273249,0.000000,1.197064,0.000000,1.191225,0.000000,1.280861,1,0
7226,0x9442DA98CA466AB70D6EB19A51515AC0,0.000000,0.000000,0.000000,1.000000,0.000000,0.929919,1.074155,1.018596,0.627205,...,0.000000,1.245108,0.000000,1.186397,0.000000,1.187708,0.000000,1.271834,1,0

In [10]:
#sanity check
for i in df_merge.columns:
    print(i)

device
00:00:00_06:45:00_x
06:45:00_11:45:00_x
11:45:00_19:15:00_x
19:15:00_23:59:59_x
Weekend/Holidays_x
d1_x
d2_x
d3_x
d4_x
d5_x
d6_x
TimeCluster_x
m1_x
b1_x
m2_x
b2_x
m3_x
b3_x
m4_x
b4_x
m5_x
b5_x
m6_x
b6_x
Séries_x
Filmes_x
Documentários_x
Informaçăo_x
Entretenimento_x
Generalistas_x
Desporto_x
Infantil_x
Outros_x
Lifestyle_x
Internacionais_x
Música_x
d_cat1_x
d_cat2_x
d_cat3_x
d_cat4_x
d_cat5_x
d_cat6_x
CatCluster_x
m_cat1_x
b_cat1_x
m_cat2_x
b_cat2_x
m_cat3_x
b_cat3_x
m_cat4_x
b_cat4_x
m_cat5_x
b_cat5_x
m_cat6_x
b_cat6_x
00:00:00_06:45:00_y
06:45:00_11:45:00_y
11:45:00_19:15:00_y
19:15:00_23:59:59_y
Weekend/Holidays_y
d1_y
d2_y
d3_y
d4_y
d5_y
d6_y
TimeCluster_y
m1_y
b1_y
m2_y
b2_y
m3_y
b3_y
m4_y
b4_y
m5_y
b5_y
m6_y
b6_y
Séries_y
Filmes_y
Documentários_y
Informaçăo_y
Entretenimento_y
Generalistas_y
Desporto_y
Infantil_y
Outros_y
Lifestyle_y
Internacionais_y
Música_y
d_cat1_y
d_cat2_y
d_cat3_y
d_cat4_y
d_cat5_y
d_cat6_y
CatCluster_y
m_cat1_y
b_cat1_y
m_cat2_y
b_cat2_y
m_cat3_y
b_cat3_y
m_cat4_y
b_cat4_y
m_cat5_y
b_cat5_y
m_cat6_y
b_cat6_y
change_TimeCluster
change_CatCluster

In [11]:
# sanity check
df_temp = df_merge[['device','change_TimeCluster', 'change_CatCluster']]
df_temp

,device,change_TimeCluster,change_CatCluster
0,0x4272D6BB7365FDB6394FC42F703839DB,0,0
1,0xCA6837254FF118AC46CDE43F1A1318CE,0,0
2,0x881C2A8AF6431AE8368AB0697A2D78EF,1,0
3,0xDC7738C974D7FDF167D2246CE1397ED2,1,0
4,0x82E30D17D0B940C0719D852F46289BCB,0,0
...,...,...,...
7222,0x458ACBCF1F2AEF82442226D7822B7922,1,0
7223,0x53025621D50B35AF1153585746252F52,1,0
7224,0xD3E0AA1A149E2992158C78B1495D1B24,1,0
7225,0x8F2AFAD07C2F016220CF3FC9607C7BC2,1,0
7226,0x9442DA98CA466AB70D6EB19A51515AC0,1,0

## b) inter-weeks distance to centroids difference - week 1 & week 2

We will now replace the distance to the centroids of each week, by the inter-weeks difference. 
We call this new feature **diff measure**.

I.e.:

**Time:**
- diff1_t = d1_y - d1_x (x represents week 1 & y represents week 2)
- diff2_t = d2_y - d2_x 
- diff3_t = d3_y - d3_x 
- diff4_t = d4_y - d4_x 
- diff5_t = d5_y - d5_x 
- diff6_t = d6_y - d6_x 

**Category:**
- diff1_c = d_cat1_y - d_cat1_x
- diff2_c = d_cat2_y - d_cat2_x
- diff3_c = d_cat3_y - d_cat3_x
- diff4_c = d_cat4_y - d_cat4_x
- diff5_c = d_cat5_y - d_cat5_x
- diff6_c = d_cat6_y - d_cat6_x

In [12]:
# add "diff" columns
df_merge['diff1_t'] = df_merge['d1_y'] - df_merge['d1_x']
df_merge['diff2_t'] = df_merge['d2_y'] - df_merge['d2_x']
df_merge['diff3_t'] = df_merge['d3_y'] - df_merge['d3_x']
df_merge['diff4_t'] = df_merge['d4_y'] - df_merge['d4_x']
df_merge['diff5_t'] = df_merge['d5_y'] - df_merge['d5_x']
df_merge['diff6_t'] = df_merge['d6_y'] - df_merge['d6_x']

df_merge['diff1_c'] = df_merge['d_cat1_y'] - df_merge['d_cat1_x']
df_merge['diff2_c'] = df_merge['d_cat2_y'] - df_merge['d_cat2_x']
df_merge['diff3_c'] = df_merge['d_cat3_y'] - df_merge['d_cat3_x']
df_merge['diff4_c'] = df_merge['d_cat4_y'] - df_merge['d_cat4_x']
df_merge['diff5_c'] = df_merge['d_cat5_y'] - df_merge['d_cat5_x']
df_merge['diff6_c'] = df_merge['d_cat6_y'] - df_merge['d_cat6_x']

In [13]:
# remove distances to centroid columns
df_merge.drop(['d1_x', 'd2_x', 'd3_x', 'd4_x', 'd5_x', 'd6_x',
               'd1_y', 'd2_y', 'd3_y', 'd4_y', 'd5_y', 'd6_y',
               'd_cat1_x', 'd_cat2_x', 'd_cat3_x', 'd_cat4_x', 'd_cat5_x', 'd_cat6_x',
               'd_cat1_y', 'd_cat2_y', 'd_cat3_y', 'd_cat4_y', 'd_cat5_y', 'd_cat6_y'], 
              axis=1, inplace=True)

In [14]:
# sanity check
for i in df_merge.columns:
    print(i)

device
00:00:00_06:45:00_x
06:45:00_11:45:00_x
11:45:00_19:15:00_x
19:15:00_23:59:59_x
Weekend/Holidays_x
TimeCluster_x
m1_x
b1_x
m2_x
b2_x
m3_x
b3_x
m4_x
b4_x
m5_x
b5_x
m6_x
b6_x
Séries_x
Filmes_x
Documentários_x
Informaçăo_x
Entretenimento_x
Generalistas_x
Desporto_x
Infantil_x
Outros_x
Lifestyle_x
Internacionais_x
Música_x
CatCluster_x
m_cat1_x
b_cat1_x
m_cat2_x
b_cat2_x
m_cat3_x
b_cat3_x
m_cat4_x
b_cat4_x
m_cat5_x
b_cat5_x
m_cat6_x
b_cat6_x
00:00:00_06:45:00_y
06:45:00_11:45:00_y
11:45:00_19:15:00_y
19:15:00_23:59:59_y
Weekend/Holidays_y
TimeCluster_y
m1_y
b1_y
m2_y
b2_y
m3_y
b3_y
m4_y
b4_y
m5_y
b5_y
m6_y
b6_y
Séries_y
Filmes_y
Documentários_y
Informaçăo_y
Entretenimento_y
Generalistas_y
Desporto_y
Infantil_y
Outros_y
Lifestyle_y
Internacionais_y
Música_y
CatCluster_y
m_cat1_y
b_cat1_y
m_cat2_y
b_cat2_y
m_cat3_y
b_cat3_y
m_cat4_y
b_cat4_y
m_cat5_y
b_cat5_y
m_cat6_y
b_cat6_y
change_TimeCluster
change_CatCluster
diff1_t
diff2_t
diff3_t
diff4_t
diff5_t
diff6_t
diff1_c
diff2_c
diff3_c
diff4_c
diff5_c
diff6_c

In [15]:
# sanity check
df_merge.shape

(7227, 101)

## features slot

This section implements a custom function that: 

**a)** filters devices with activity in the two weeks (current & next week) & 

**b)** tracks devices' migration (do they change cluster?) 

**c)** computes the inter-weeks difference regarding the distance to centroids

In [16]:
# auxiliary function to add binary labels
def binary_label(x):
    if x == 0: 
        return 0 # device does not change cluster
    else:
        return 1 # device does change cluster

In [17]:
def features(df_currentWeek, df_nextWeek):
    """
    This function:
    a) filters devices with activity in the two weeks (current & next week) 
    b) tracks devices' migration (do they change cluster? 0/1)
    c) replaces the distances to the centroids by the inter-weeks difference
    """
    # merge weeks based on devices that have activity on both periods (inner join)
    df_merge = pd.merge(df_currentWeek, df_nextWeek, how='inner', left_on='device', right_on='device')
    
    # add "change" columns to df_features
    df_merge['change_TimeCluster'] = df_merge['TimeCluster_x'] - df_merge['TimeCluster_y']
    df_merge['change_TimeCluster'] = df_merge['change_TimeCluster'].apply(binary_label)

    df_merge['change_CatCluster'] = df_merge['CatCluster_x'] - df_merge['CatCluster_y']
    df_merge['change_CatCluster'] = df_merge['change_CatCluster'].apply(binary_label)
    
    # add "diff" columns
    df_merge['diff1_t'] = df_merge['d1_y'] - df_merge['d1_x']
    df_merge['diff2_t'] = df_merge['d2_y'] - df_merge['d2_x']
    df_merge['diff3_t'] = df_merge['d3_y'] - df_merge['d3_x']
    df_merge['diff4_t'] = df_merge['d4_y'] - df_merge['d4_x']
    df_merge['diff5_t'] = df_merge['d5_y'] - df_merge['d5_x']
    df_merge['diff6_t'] = df_merge['d6_y'] - df_merge['d6_x']

    df_merge['diff1_c'] = df_merge['d_cat1_y'] - df_merge['d_cat1_x']
    df_merge['diff2_c'] = df_merge['d_cat2_y'] - df_merge['d_cat2_x']
    df_merge['diff3_c'] = df_merge['d_cat3_y'] - df_merge['d_cat3_x']
    df_merge['diff4_c'] = df_merge['d_cat4_y'] - df_merge['d_cat4_x']
    df_merge['diff5_c'] = df_merge['d_cat5_y'] - df_merge['d_cat5_x']
    df_merge['diff6_c'] = df_merge['d_cat6_y'] - df_merge['d_cat6_x']
    
    # remove distances to centroid columns
    #df_merge.drop(['d1_x', 'd2_x', 'd3_x', 'd4_x', 'd5_x', 'd6_x',
                   #'d1_y', 'd2_y', 'd3_y', 'd4_y', 'd5_y', 'd6_y',
                   #'d_cat1_x', 'd_cat2_x', 'd_cat3_x', 'd_cat4_x', 'd_cat5_x', 'd_cat6_x',
                   #'d_cat1_y', 'd_cat2_y', 'd_cat3_y', 'd_cat4_y', 'd_cat5_y', 'd_cat6_y'], 
                  #axis=1, inplace=True)
    
    # remove labels
    df_merge.drop(['TimeCluster_x','TimeCluster_y','CatCluster_x','CatCluster_y'],
                  axis=1, inplace=True)
    
    return df_merge

In [18]:
# example: slot_features for fold_1 > train_1
slot_features = features(df_w1, df_w2)

# sanity check
for i in slot_features.columns:
    print(i)

device
00:00:00_06:45:00_x
06:45:00_11:45:00_x
11:45:00_19:15:00_x
19:15:00_23:59:59_x
Weekend/Holidays_x
d1_x
d2_x
d3_x
d4_x
d5_x
d6_x
m1_x
b1_x
m2_x
b2_x
m3_x
b3_x
m4_x
b4_x
m5_x
b5_x
m6_x
b6_x
Séries_x
Filmes_x
Documentários_x
Informaçăo_x
Entretenimento_x
Generalistas_x
Desporto_x
Infantil_x
Outros_x
Lifestyle_x
Internacionais_x
Música_x
d_cat1_x
d_cat2_x
d_cat3_x
d_cat4_x
d_cat5_x
d_cat6_x
m_cat1_x
b_cat1_x
m_cat2_x
b_cat2_x
m_cat3_x
b_cat3_x
m_cat4_x
b_cat4_x
m_cat5_x
b_cat5_x
m_cat6_x
b_cat6_x
00:00:00_06:45:00_y
06:45:00_11:45:00_y
11:45:00_19:15:00_y
19:15:00_23:59:59_y
Weekend/Holidays_y
d1_y
d2_y
d3_y
d4_y
d5_y
d6_y
m1_y
b1_y
m2_y
b2_y
m3_y
b3_y
m4_y
b4_y
m5_y
b5_y
m6_y
b6_y
Séries_y
Filmes_y
Documentários_y
Informaçăo_y
Entretenimento_y
Generalistas_y
Desporto_y
Infantil_y
Outros_y
Lifestyle_y
Internacionais_y
Música_y
d_cat1_y
d_cat2_y
d_cat3_y
d_cat4_y
d_cat5_y
d_cat6_y
m_cat1_y
b_cat1_y
m_cat2_y
b_cat2_y
m_cat3_y
b_cat3_y
m_cat4_y
b_cat4_y
m_cat5_y
b_cat5_y
m_cat6_y
b_cat6_y
change_TimeCluster
change_CatCluster
diff1_t
diff2_t
diff3_t
diff4_t
diff5_t
diff6_t
diff1_c
diff2_c
diff3_c
diff4_c
diff5_c
diff6_c

In [19]:
# sanity check
slot_features.shape

(7227, 121)

In [20]:
slot_features['change_CatCluster']

0       0
1       1
2       0
3       1
4       0
       ..
7222    0
7223    1
7224    0
7225    1
7226    0
Name: change_CatCluster, Length: 7227, dtype: int64

# Labels slot

In this section, we prepare the labels' slot.

In [21]:
# STEP 1 
df_features_devices = slot_features['device'] # devices with activity in the features'weeks
df_labels = pd.merge(df_features_devices, df_w3, how='left', left_on='device', right_on='device')

# sanity check
print(df_labels.shape)
print(df_labels.columns)

(7227, 56)
Index(['device', '00:00:00_06:45:00', '06:45:00_11:45:00', '11:45:00_19:15:00',
       '19:15:00_23:59:59', 'Weekend/Holidays', 'd1', 'd2', 'd3', 'd4', 'd5',
       'd6', 'TimeCluster', 'm1', 'b1', 'm2', 'b2', 'm3', 'b3', 'm4', 'b4',
       'm5', 'b5', 'm6', 'b6', 'Séries', 'Filmes', 'Documentários',
       'Informaçăo', 'Entretenimento', 'Generalistas', 'Desporto', 'Infantil',
       'Outros', 'Lifestyle', 'Internacionais', 'Música', 'd_cat1', 'd_cat2',
       'd_cat3', 'd_cat4', 'd_cat5', 'd_cat6', 'CatCluster', 'm_cat1',
       'b_cat1', 'm_cat2', 'b_cat2', 'm_cat3', 'b_cat3', 'm_cat4', 'b_cat4',
       'm_cat5', 'b_cat5', 'm_cat6', 'b_cat6'],
      dtype='object')

In [22]:
# STEP 2
# keep only the columns: 'device', 'TimeCluster', 'CatCluster'
df_labels = df_labels[['device', 'TimeCluster', 'CatCluster']]
df_labels

                                  device  TimeCluster  CatCluster
0     0x4272D6BB7365FDB6394FC42F703839DB          3.0         4.0
1     0xCA6837254FF118AC46CDE43F1A1318CE          4.0         2.0
2     0x881C2A8AF6431AE8368AB0697A2D78EF          3.0         5.0
3     0xDC7738C974D7FDF167D2246CE1397ED2          6.0         2.0
4     0x82E30D17D0B940C0719D852F46289BCB          4.0         2.0
...                                  ...          ...         ...
7222  0x458ACBCF1F2AEF82442226D7822B7922          NaN         NaN
7223  0x53025621D50B35AF1153585746252F52          NaN         NaN
7224  0xD3E0AA1A149E2992158C78B1495D1B24          NaN         NaN
7225  0x8F2AFAD07C2F016220CF3FC9607C7BC2          NaN         NaN
7226  0x9442DA98CA466AB70D6EB19A51515AC0          NaN         NaN

[7227 rows x 3 columns]

We also add 2 new labels: **"Change_TimeCluster"** & **"Change_CatCluster"**.

Each one has 3 classes that, regarding the week previous to the week label, identify:

- **"0"**, devices that don't change cluster
- **"1"**, devices that change cluster
- **"missing"**, devices that do not have activity

In [23]:
# auxiliary function to add binary labels
def binary_label(x):
    if x == 0: 
        return 0 # device does not change cluster
    elif (x>0 or x<0):
        return 1  # device does change cluster
    else:
        return "missing"

In [24]:
# STEP 3
# new labels: "Change_TimeCluster" & "Change_CatCluster" 
df_labels = pd.merge(df_labels, df_w2, how='left', left_on='device', right_on='device')

# add "change" columns to df_labels
df_labels['Change_TimeCluster'] = df_labels['TimeCluster_x'] - df_labels['TimeCluster_y'] #**
df_labels['Change_TimeCluster'] = df_labels['Change_TimeCluster'].apply(binary_label) # add binary label
#** the device does not change cluster only if this difference is equal to 0

df_labels['Change_CatCluster'] = df_labels['CatCluster_x'] - df_labels['CatCluster_y']
df_labels['Change_CatCluster'] = df_labels['Change_CatCluster'].apply(binary_label)

df_labels

,device,TimeCluster_x,CatCluster_x,00:00:00_06:45:00,06:45:00_11:45:00,11:45:00_19:15:00,19:15:00_23:59:59,Weekend/Holidays,d1,d2,...,m_cat3,b_cat3,m_cat4,b_cat4,m_cat5,b_cat5,m_cat6,b_cat6,Change_TimeCluster,Change_CatCluster
0,0x4272D6BB7365FDB6394FC42F703839DB,3.0,4.0,0.370670,0.000000,0.000000,0.467003,0.162326,0.549703,0.691943,...,0.000306,0.773360,0.000223,0.544427,0.000339,0.676097,0.000306,0.811440,1,0
1,0xCA6837254FF118AC46CDE43F1A1318CE,4.0,2.0,0.000000,0.000000,0.415804,0.584196,0.000000,0.590060,0.879573,...,0.000000,1.067325,0.000000,0.943002,0.000000,0.981589,0.000000,0.159367,0,1
2,0x881C2A8AF6431AE8368AB0697A2D78EF,3.0,5.0,0.452035,0.044959,0.000000,0.000000,0.503006,0.528110,0.496778,...,-0.000339,0.760919,-0.000495,0.657022,0.002090,0.648800,-0.001063,0.808443,0,1
3,0xDC7738C974D7FDF167D2246CE1397ED2,6.0,2.0,0.002040,0.180756,0.107912,0.449839,0.259453,0.343132,0.538190,...,0.000311,0.760789,0.000421,0.668139,-0.000974,0.655101,0.000222,0.805186,1,0
4,0x82E30D17D0B940C0719D852F46289BCB,4.0,2.0,0.280200,0.000000,0.073915,0.406388,0.239497,0.399246,0.562808,...,0.000351,0.759864,0.002433,0.657248,0.003036,0.649222,-0.000368,0.807025,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7222,0x458ACBCF1F2AEF82442226D7822B7922,NaN,NaN,0.000000,0.000000,0.000000,1.000000,0.000000,0.929919,1.074155,...,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879,missing,missing
7223,0x53025621D50B35AF1153585746252F52,NaN,NaN,0.000000,0.000000,0.000000,1.000000,0.000000,0.929919,1.074155,...,0.000000,0.273249,0.000000,1.197064,0.000000,1.191225,0.000000,1.280861,missing,missing
7224,0xD3E0AA1A149E2992158C78B1495D1B24,NaN,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.671133,0.363276,...,0.000000,1.172346,0.000000,1.049871,0.000000,1.035727,0.000000,1.222879,missing,missing
7225,0x8F2AFAD07C2F016220CF3FC9607C7BC2,NaN,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,0.889257,1.186560,...,0.000000,0.273249,0.000000,1.197064,0.000000,1.191225,0.000000,1.280861,missing,missing
7226,0x9442DA98CA466AB70D6EB19A51515AC0,NaN,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,0.889257,1.186560,...,0.000000,1.245108,0.000000,1.186397,0.000000,1.187708,0.000000,1.271834,missing,missing

In [25]:
df_labels.columns

Index(['device', 'TimeCluster_x', 'CatCluster_x', '00:00:00_06:45:00',
       '06:45:00_11:45:00', '11:45:00_19:15:00', '19:15:00_23:59:59',
       'Weekend/Holidays', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'TimeCluster_y',
       'm1', 'b1', 'm2', 'b2', 'm3', 'b3', 'm4', 'b4', 'm5', 'b5', 'm6', 'b6',
       'Séries', 'Filmes', 'Documentários', 'Informaçăo', 'Entretenimento',
       'Generalistas', 'Desporto', 'Infantil', 'Outros', 'Lifestyle',
       'Internacionais', 'Música', 'd_cat1', 'd_cat2', 'd_cat3', 'd_cat4',
       'd_cat5', 'd_cat6', 'CatCluster_y', 'm_cat1', 'b_cat1', 'm_cat2',
       'b_cat2', 'm_cat3', 'b_cat3', 'm_cat4', 'b_cat4', 'm_cat5', 'b_cat5',
       'm_cat6', 'b_cat6', 'Change_TimeCluster', 'Change_CatCluster'],
      dtype='object')

In [26]:
# STEP 4
# add the label "missing" 

df_labels['TimeCluster_x'].fillna('missing', inplace=True)
df_labels['CatCluster_x'].fillna('missing', inplace=True)

df_labels['Change_TimeCluster'].fillna('missing', inplace=True)
df_labels['Change_CatCluster'].fillna('missing', inplace=True)

# keep only the columns "device", 'TimeCluster_x', 'CatCluster_x', 
# 'Change_TimeCluster', 'Change_CatCluster'

df_labels = df_labels[['device', 'TimeCluster_x', 'CatCluster_x', 'Change_TimeCluster', 'Change_CatCluster' ]]
df_labels = df_labels.rename(columns = {'TimeCluster_x': 'TimeCluster_lab', 'CatCluster_x': 'CatCluster_lab','Change_TimeCluster': 'Change_TimeCluster_lab','Change_CatCluster': 'Change_CatCluster_lab'}, inplace = False)

df_labels

,device,TimeCluster_lab,CatCluster_lab,Change_TimeCluster_lab,Change_CatCluster_lab
0,0x4272D6BB7365FDB6394FC42F703839DB,3.0,4.0,1,0
1,0xCA6837254FF118AC46CDE43F1A1318CE,4.0,2.0,0,1
2,0x881C2A8AF6431AE8368AB0697A2D78EF,3.0,5.0,0,1
3,0xDC7738C974D7FDF167D2246CE1397ED2,6.0,2.0,1,0
4,0x82E30D17D0B940C0719D852F46289BCB,4.0,2.0,0,0
...,...,...,...,...,...
7222,0x458ACBCF1F2AEF82442226D7822B7922,missing,missing,missing,missing
7223,0x53025621D50B35AF1153585746252F52,missing,missing,missing,missing
7224,0xD3E0AA1A149E2992158C78B1495D1B24,missing,missing,missing,missing
7225,0x8F2AFAD07C2F016220CF3FC9607C7BC2,missing,missing,missing,missing
7226,0x9442DA98CA466AB70D6EB19A51515AC0,missing,missing,missing,missing

Gathering the previous steps in a custom function:

In [27]:
def labels(slot_features, df_previous_week, df_week_label):
    """
    This function prepares the labels slot.
    """
    # STEP 1 
    df_features_devices = slot_features['device'] # devices with activity in the features'weeks
    df_labels = pd.merge(df_features_devices, df_week_label, how='left', left_on='device', right_on='device')
    
    # STEP 2
    df_labels = df_labels[['device', 'TimeCluster', 'CatCluster']]
    
    # STEP 3
    # new labels: "Change_TimeCluster" & "Change_CatCluster" 
    df_labels = pd.merge(df_labels, df_previous_week, how='left', left_on='device', right_on='device')

    # add "change" columns to df_labels
    df_labels['Change_TimeCluster'] = df_labels['TimeCluster_x'] - df_labels['TimeCluster_y'] #**
    df_labels['Change_TimeCluster'] = df_labels['Change_TimeCluster'].apply(binary_label) # add binary label
    #** the device does not change cluster only if this difference is equal to 0

    df_labels['Change_CatCluster'] = df_labels['CatCluster_x'] - df_labels['CatCluster_y']
    df_labels['Change_CatCluster'] = df_labels['Change_CatCluster'].apply(binary_label)
    
    # STEP 4
    # add the label "missing" 

    df_labels['TimeCluster_x'].fillna('missing', inplace=True)
    df_labels['CatCluster_x'].fillna('missing', inplace=True)

    df_labels['Change_TimeCluster'].fillna('missing', inplace=True)
    df_labels['Change_CatCluster'].fillna('missing', inplace=True)

    # keep only the columns "device", 'TimeCluster_x', 'CatCluster_x', 
    # 'Change_TimeCluster', 'Change_CatCluster'

    df_labels = df_labels[['device', 'TimeCluster_x', 'CatCluster_x', 'Change_TimeCluster', 'Change_CatCluster' ]]
    df_labels = df_labels.rename(columns = {'TimeCluster_x': 'TimeCluster_lab', 'CatCluster_x': 'CatCluster_lab',
                                            'Change_TimeCluster': 'Change_TimeCluster_lab',
                                            'Change_CatCluster': 'Change_CatCluster_lab',}, inplace = False)
    
    return df_labels

In [28]:
# example slot_labels for week 3
slot_labels = labels(slot_features, df_w2, df_w3)

slot_labels

,device,TimeCluster_lab,CatCluster_lab,Change_TimeCluster_lab,Change_CatCluster_lab
0,0x4272D6BB7365FDB6394FC42F703839DB,3.0,4.0,1,0
1,0xCA6837254FF118AC46CDE43F1A1318CE,4.0,2.0,0,1
2,0x881C2A8AF6431AE8368AB0697A2D78EF,3.0,5.0,0,1
3,0xDC7738C974D7FDF167D2246CE1397ED2,6.0,2.0,1,0
4,0x82E30D17D0B940C0719D852F46289BCB,4.0,2.0,0,0
...,...,...,...,...,...
7222,0x458ACBCF1F2AEF82442226D7822B7922,missing,missing,missing,missing
7223,0x53025621D50B35AF1153585746252F52,missing,missing,missing,missing
7224,0xD3E0AA1A149E2992158C78B1495D1B24,missing,missing,missing,missing
7225,0x8F2AFAD07C2F016220CF3FC9607C7BC2,missing,missing,missing,missing
7226,0x9442DA98CA466AB70D6EB19A51515AC0,missing,missing,missing,missing

# Generating the slots (features & labels) for the predictive models

## fold 1

In [29]:
# train_features: week 1 & week 2
# train_labels: week 3
slot_features_train = features(df_w1, df_w2)
slot_labels_train = labels(slot_features_train, df_w2, df_w3)

fold1_train = pd.merge(slot_features_train , slot_labels_train, how='inner', left_on='device', 
                       right_on='device')

fold1_train.to_csv('folder1_train.csv', index=False)

# valid_features: week 2 & week 3
# valid_labels: week 4
slot_features_valid = features(df_w2, df_w3)
slot_labels_valid = labels(slot_features_valid, df_w3, df_w4)

fold1_valid = pd.merge(slot_features_valid , slot_labels_valid, how='inner', left_on='device', 
                       right_on='device')

fold1_valid.to_csv('folder1_valid.csv', index=False)


# test_features: week 3 & week 4
# test_labels: week 5
slot_features_test = features(df_w3, df_w4)
slot_labels_test = labels(slot_features_test, df_w4, df_w5)

fold1_test = pd.merge(slot_features_test , slot_labels_test, how='inner', left_on='device', 
                       right_on='device')

fold1_test.to_csv('folder1_test.csv', index=False)

## fold 2

In [30]:
# train_features: week 2 & week 3
# train_labels: week 4
slot_features_train = features(df_w2, df_w3)
slot_labels_train = labels(slot_features_train, df_w3, df_w4)

fold2_train = pd.merge(slot_features_train , slot_labels_train, how='inner', left_on='device', 
                       right_on='device')

fold2_train.to_csv('folder2_train.csv', index=False)

# valid_features: week 3 & week 4
# valid_labels: week 5
slot_features_valid = features(df_w3, df_w4)
slot_labels_valid = labels(slot_features_valid, df_w4, df_w5)

fold2_valid = pd.merge(slot_features_valid , slot_labels_valid, how='inner', left_on='device', 
                       right_on='device')

fold2_valid.to_csv('folder2_valid.csv', index=False)


# test_features: week 4 & week 5
# test_labels: week 6
slot_features_test = features(df_w4, df_w5)
slot_labels_test = labels(slot_features_test, df_w5, df_w6)

fold2_test = pd.merge(slot_features_test , slot_labels_test, how='inner', left_on='device', 
                       right_on='device')

fold2_test.to_csv('folder2_test.csv', index=False)

## fold 3

In [31]:
# train_features: week 3 & week 4
# train_labels: week 5
slot_features_train = features(df_w3, df_w4)
slot_labels_train = labels(slot_features_train, df_w4, df_w5)

fold3_train = pd.merge(slot_features_train , slot_labels_train, how='inner', left_on='device', 
                       right_on='device')

fold3_train.to_csv('folder3_train.csv', index=False)

# valid_features: week 4 & week 5
# valid_labels: week 6
slot_features_valid = features(df_w4, df_w5)
slot_labels_valid = labels(slot_features_valid, df_w5, df_w6)

fold3_valid = pd.merge(slot_features_valid , slot_labels_valid, how='inner', left_on='device', 
                       right_on='device')

fold3_valid.to_csv('folder3_valid.csv', index=False)

# test_features: week 5 & week 6
# test_labels: week 7
slot_features_test = features(df_w5, df_w6)
slot_labels_test = labels(slot_features_test, df_w6, df_w7)

fold3_test = pd.merge(slot_features_test , slot_labels_test, how='inner', left_on='device', 
                       right_on='device')

fold3_test.to_csv('folder3_test.csv', index=False)

## fold 4

In [32]:
# train_features: week 4 & week 5
# train_labels: week 6
slot_features_train = features(df_w4, df_w5)
slot_labels_train = labels(slot_features_train, df_w5, df_w6)

fold4_train = pd.merge(slot_features_train , slot_labels_train, how='inner', left_on='device', 
                       right_on='device')

fold4_train.to_csv('folder4_train.csv', index=False)

# valid_features: week 5 & week 6
# valid_labels: week 7
slot_features_valid = features(df_w5, df_w6)
slot_labels_valid = labels(slot_features_valid, df_w6, df_w7)


fold4_valid = pd.merge(slot_features_valid , slot_labels_valid, how='inner', left_on='device', 
                       right_on='device')

fold4_valid.to_csv('folder4_valid.csv', index=False)

# test_features: week 6 & week 7
# test_labels: week 8
slot_features_test = features(df_w6, df_w7)
slot_labels_test = labels(slot_features_test, df_w7, df_w8)

fold4_test = pd.merge(slot_features_test , slot_labels_test, how='inner', left_on='device', 
                       right_on='device')

fold4_test.to_csv('folder4_test.csv', index=False)

## fold 5

In [33]:
# train_features: week 5 & week 6
# train_labels: week 7
slot_features_train = features(df_w5, df_w6)
slot_labels_train = labels(slot_features_train, df_w6, df_w7)

fold5_train = pd.merge(slot_features_train , slot_labels_train, how='inner', left_on='device', 
                       right_on='device')

fold5_train.to_csv('folder5_train.csv', index=False)

# valid_features: week 6 & week 7
# valid_labels: week 8
slot_features_valid = features(df_w6, df_w7)
slot_labels_valid = labels(slot_features_valid, df_w7, df_w8)

fold5_valid = pd.merge(slot_features_valid , slot_labels_valid, how='inner', left_on='device', 
                       right_on='device')

fold5_valid.to_csv('folder5_valid.csv', index=False)

# test_features: week 7 & week 8
# test_labels: week 9
slot_features_test = features(df_w7, df_w8)
slot_labels_test = labels(slot_features_test, df_w8, df_w9)

fold5_test = pd.merge(slot_features_test , slot_labels_test, how='inner', left_on='device', 
                       right_on='device')

fold5_test.to_csv('folder5_test.csv', index=False)

## fold 6

In [34]:
# train_features: week 6 & week 7
# train_labels: week 8
slot_features_train = features(df_w6, df_w7)
slot_labels_train = labels(slot_features_train, df_w7, df_w8)

fold6_train = pd.merge(slot_features_train , slot_labels_train, how='inner', left_on='device', 
                       right_on='device')

fold6_train.to_csv('folder6_train.csv', index=False)

# valid_features: week 7 & week 8
# valid_labels: week 9
slot_features_valid = features(df_w7, df_w8)
slot_labels_valid = labels(slot_features_valid, df_w8, df_w9)

fold6_valid = pd.merge(slot_features_valid , slot_labels_valid, how='inner', left_on='device', 
                       right_on='device')

fold6_valid.to_csv('folder6_valid.csv', index=False)

# test_features: week 8 & week 9
# test_labels: week 10
slot_features_test = features(df_w8, df_w9)
slot_labels_test = labels(slot_features_test, df_w9, df_w10)

fold6_test = pd.merge(slot_features_test , slot_labels_test, how='inner', left_on='device', 
                       right_on='device')

fold6_test.to_csv('folder6_test.csv', index=False)